-- Table: tickets

-- DROP TABLE tickets;

CREATE TABLE tickets
(
  serial bigint,
  type smallint,
  checksum smallint,
  partial_record_indicator smallint,
  clock_changed_flag smallint,
  free_flag smallint,
  validity smallint,
  call_attempt_flag smallint,
  compliant_flag smallint,
  centralized_charging_flag smallint,
  pps smallint,
  charging_method smallint,
  npc smallint,
  payer smallint,
  end_time timestamp without time zone,
  duration bigint,
  caller_seizure_duration bigint,
  called_seizure_duration bigint,
  incomplete_call_watch smallint,
  caller_isdn smallint,
  called_isdn smallint,
  isup smallint,
  flag3_reserved smallint,
  charging_nature smallint,
  caller_nature smallint,
  connected_nature smallint,
  called_nature smallint,
  charging_number_set smallint,
  charging_number character varying(25),
  caller_number_set smallint,
  caller_number character varying(25),
  connected_number_set smallint,
  connected_number character varying(25),
  called_number_set smallint,
  called_number character varying(25),
  dialed_number character varying(25),
  group_number integer,
  caller_short_number bigint,
  called_short_number bigint,
  caller_module_number smallint,
  called_module_number smallint,
  incoming_trunk_gn integer,
  outgoing_trunk_gn integer,
  incoming_subroute_number integer,
  outgoing_subroute_number integer,
  caller_device_type smallint,
  called_device_type smallint,
  caller_port_number integer,
  called_port_number integer,
  caller_category smallint,
  called_category smallint,
  call_type smallint,
  service_type smallint,
  supplementary_service_type smallint,
  charging_case integer,
  tariff integer,
  charging_pulse bigint,
  fee bigint,
  balance smallint,
  bearer_service smallint,
  teleservice smallint,
  release_party smallint,
  release_index smallint,
  release_cause smallint,
  uus1 smallint,
  uus2 smallint,
  uus3 smallint,
  opc bigint,
  dpc bigint,
  b_num smallint,
  b_num_reserved smallint
);
